name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: setup tools
        run: sudo apt-get install --yes libxml2-utils
      - uses: actions/checkout@v1
      - name: validate
        run: make validate
